export const CONTENT_GET = 'CONTENT_GET';
export const CONTENT_LIST = 'CONTENT_LIST';
export const CONTENT_CREATE = 'CONTENT_CREATE';
export const CONTENT_UPDATE = 'CONTENT_UPDATE';
export const CONTENT_DELETE = 'CONTENT_DELETE';
