export { default as Authorize } from './Authorize';
export { default as CollectionsPage } from './CollectionsPage';
export { default as CollectionPage } from './CollectionPage';
export { default as ErrorPage } from './ErrorPage';
export { default as HomePage } from './HomePage';
export { default as Login } from './Login';
export { default as NotFoundPage } from './NotFoundPage';
export { default as SpacesPage } from './SpacesPage';
export { default as UsersPage } from './UsersPage';
