language: node_js

node_js:
  - stable

cache:
  directories:
  - node_modules

script:
  - npm install -g travis-ci-cloudfront-invalidation
  - npm install
  - npm test
  - npm run build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET_NAME
  skip_cleanup: true
  acl: public_read
  region: $AWS_REGION
  local_dir: build
  on:
    branch: master

after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $AWS_CLOUDFRONT_DISTRIBUTION_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST
