export const COLLECTION_ITEM = 'COLLECTION_ITEM';
export const COLLECTION_LIST = 'COLLECTION_LIST';
export const COLLECTION_CREATE = 'COLLECTION_CREATE';
export const COLLECTION_UPDATE = 'COLLECTION_UPDATE';
