export const COLLECTIONS_GET = 'COLLECTIONS_GET';
export const COLLECTIONS_LIST = 'COLLECTIONS_LIST';
export const COLLECTIONS_CREATE = 'COLLECTIONS_CREATE';
export const COLLECTIONS_UPDATE = 'COLLECTIONS_UPDATE';
export const COLLECTIONS_DELETE = 'COLLECTIONS_DELETE';
