export const COLLECTIONS_ITEM = 'COLLECTIONS_ITEM';
export const COLLECTIONS_LIST = 'COLLECTIONS_LIST';
export const COLLECTIONS_CREATE = 'COLLECTIONS_CREATE';
export const COLLECTIONS_UPDATE = 'COLLECTIONS_UPDATE';
export const COLLECTIONS_DELETE = 'COLLECTIONS_DELETE';
