export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const PROFILE_GET = 'PROFILE_GET';
export const PROFILE_UPDATE = 'PROFILE_UPDATE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
